### ISSUE TITLE
DialogueContinueSession and DialogueEndSession classes don't need site_id

### ISSUE THREAD

**Issue by koenvervloesem** [rhasspy/rhasspy-hermes#10]
According to the [Hermes Protocol documentation](https://docs.snips.ai/reference/dialogue#end-session) `hermes/dialogueManager/continueSession` and `hermes/dialogueManager/endSession` don't need a `site_id` property. Is there a reason why it's included in rhasspy-hermes? I think it doesn't make sense to specify the `site_id` in these classes because the [dialogue manager](https://github.com/rhasspy/rhasspy-dialogue-hermes/blob/master/rhasspydialogue_hermes/__init__.py) uses the `site_id` of the original session that is continued or ended. Or am I missing something?

**Comment by synesthesiam** [comment]
You're right. I did this to make debugging easier on myself when dealing with multiple satellites. The dialogue manager has a mapping of `session_id` back to `site_id`, but my brain doesn't :)

**Comment by koenvervloesem** [comment]
Solved in https://github.com/rhasspy/rhasspy-hermes/commit/eac05108b8cf7e949d9a81c497f78113c221f6a7.
