### ISSUE TITLE
Why is the session ID of an NluIntent optional?

### ISSUE THREAD

**Issue by koenvervloesem** [rhasspy/rhasspy-hermes#13]
According to the [Hermes protocol documentation](https://docs.snips.ai/reference/dialogue#payload), a `hermes/intent/<intentName>` message has a non-optional sessionId in its payload.

I see that the [NluIntent](https://github.com/rhasspy/rhasspy-hermes/blob/master/rhasspyhermes/nlu.py) class in rhasspy-hermes has defined the `session_id` attribute as optional. Why is this?

**Comment by synesthesiam** [comment]
I went back and forth on this, but ultimately decided to go against the Hermes docs. I think the NLU components are usable in isolation without any dialogue manager, so I saw no reason to require a session ID in the message.

As long as each NLU service simply copies the session ID from a query to the outgoing intent messages, all should be well regardless of whether the message is coming from a dialogue manager or the command line :)

**Comment by koenvervloesem** [comment]
Ok, that makes sense! I'll document this difference with the Snips Hermes spec when I'll work on the Rhasspy Hermes documentation.

**Comment by koenvervloesem** [comment]
Fixed in https://github.com/rhasspy/rhasspy-hermes/commit/e191dbe1b256044aa36a0bc5121c56bf400327a8
