### ISSUE TITLE
DialogueContinueSession - not possible to get ASR audio captured

### ISSUE THREAD

**Issue by tuxedo78** [rhasspy/rhasspy-hermes#14]
When continuing an ongoing session, it's not possible to ask Rhasspy to provide the audio captured (with rhasspy/asr/<SITE_ID>/<SESSION_ID>/audioCaptured) because there is no flag to enable this when ASR starts listening the the next topic.

**Comment by synesthesiam** [comment]
Should be fixed in https://github.com/rhasspy/rhasspy-dialogue-hermes/commit/360278e1ba68b8c4bfbae3725d77c5b6b710d1f5
