### ISSUE TITLE
Why do NluQuery, NluIntentParsed, NluIntentNotRecognized and NluError have a site id?

### ISSUE THREAD

**Issue by koenvervloesem** [rhasspy/rhasspy-hermes#18]
In the original Snips Hermes protocol documentation, `hermes/nlu/query` [doesn't have a site ID](https://docs.snips.ai/reference/hermes#sending-text-to-the-nlu-component). Why does the `NluQuery` class have this attribute? The same holds for `NluIntentParsed`, `NluIntentNotRecognized` and `NluError`.

**Comment by synesthesiam** [comment]
Rhasspy needs site IDs for most messages to support satellites and multiple services of the same type. You can run multiple NLU services, each with a different site ID, and direct queries to either of them.

**Comment by koenvervloesem** [comment]
Ok that makes sense, I'll clarify that in the documentation.

**Comment by koenvervloesem** [comment]
Fixed in https://github.com/rhasspy/rhasspy-hermes/commit/e191dbe1b256044aa36a0bc5121c56bf400327a8
