### ISSUE TITLE
Test infrastructure

### ISSUE THREAD

**Issue by koenvervloesem** [rhasspy/rhasspy-hermes#2]
I propose some changes to structure the tests (this would be for all Rhasspy repositories, but I'm using this one now as a 'test case', see also https://github.com/rhasspy/rhasspy-hermes/pull/1):

# Tests instead of test

I would use `tests` instead of `test` for the test directory:

- For consistency: You'd also use `docs` and not `doc`.
- To prevent name clashes with Python's [test](https://docs.python.org/3/library/test.html) module.
- To follow good integration practices: I see more developers in favour of `tests` than `test`. See the following links for both viewpoints:
  - https://stackoverflow.com/questions/61151/where-do-the-python-unit-tests-go/23386287#23386287
  - https://docs.python.org/3/library/unittest.html
  - https://gist.github.com/tasdikrahman/2bdb3fb31136a3768fac
  - https://docs.python-guide.org/writing/structure/
  - https://docs.pytest.org/en/latest/goodpractices.html

# test_*.py instead of __init__.py

I would use `test_*.py` files for the test code instead of the generic `__init__.py`:

- For consistency: You could split tests in multiple files later.
- To follow good integration practices linked above.

# Discussion

Some questions to consider:

- Keep using [unittest](https://docs.python.org/3/library/unittest.html) or migrate to [pytest](https://docs.pytest.org/en/latest/contents.html)? Pytest has a more compact style, so you don't need unittest classes. It's also highly extensible. But maybe we don't need it (yet).
- Look at [tox](https://tox.readthedocs.io/) to automate testing?

**Comment by synesthesiam** [comment]
I'm fine with migrating to `pytest` and exploring `tox`. I don't really know its full capabilities besides using different Python versions.

Part of what makes some kinds of testing in Rhasspy difficult is the need to pull down large binary artifacts (speech models, etc.). Travis CI will need to pull these from GitHub. A good first pass is to get things automated with English.

**Comment by koenvervloesem** [comment]
You're also OK with renaming `test` to `tests` and `__init__.py` to `test_*.py`?

By the way, I'm now just starting with this simple repository to lay the foundations of a robust test approach for Rhasspy. After this, I'll work my way up to other repositories that are progressively more difficult to test.

At some point we'll probably even need integration tests to test integration between various services.

**Comment by synesthesiam** [comment]
> You're also OK with renaming test to tests and __init__.py to test_*.py?

Yes, I've made similar changes recently to `rhasspy_nlu`.

**Comment by koenvervloesem** [comment]
Fixed the naming in https://github.com/rhasspy/rhasspy-hermes/pull/1.
